application: nokia-5500
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /fetch\.py
  script: wsgi_old.app
  secure: optional

- url: /2
  script: wsgi.gae_application
  secure: optional

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
